name: Execution des scénarios de test API - CI
on:
  push:
   # branches: [ mainY ]    est-ce que je peux faire les deux run manuel et auto ?  
  workflow_dispatch: 
  pull_request:
    branches: [ mainY ]
  # pas mis de workflow call  , code Zak
jobs:
 test:   # nom du job
    timeout-minutes: 60
    runs-on: macos-latest  # runner ? 
    steps:
    #- name: pre/post clean   # je ne maitrise pas
      #id: clean
     # uses: xxx/.github/actions/cleaner@main 
    - uses: actions/checkout@v4   # recupère l'historique complet, pourquoi faire? 
      id: checkout   
      with:
        fetch-depth: 0 
    - uses: actions/setup-node@v4 # instal Node.js LTS pour exécuter Playwright.
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm install  # installation complete avec les dependance 
    - name: Install Playwright 
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test
      #env:
      #  PLAYWRIGHT_TEST_BASE_URL: ${{ github.event.deployment_status.target_url }}






        